/* ---------- OS v2 ---------- */
const WPIMG=window.EMBEDDED_ASSETS.wallpaper;
const WP=[['Spotifly','#47b06f url('+WPIMG+') center/cover no-repeat'],['Sunset','linear-gradient(#ff7e5f,#feb47b 50%,#6a3093)'],['Midnight','linear-gradient(#0f2027,#203a43,#2c5364)'],['Synthwave','linear-gradient(#2b0a4a,#d62fa0 60%,#ffb347)'],['Pixel grid','repeating-linear-gradient(0deg,#0007 0 2px,transparent 2px 24px),repeating-linear-gradient(90deg,#0007 0 2px,transparent 2px 24px),#2a6f97'],['Forest','linear-gradient(#134e4a,#166534 60%,#052e16)'],['Ocean','linear-gradient(#0ea5e9,#0369a1 60%,#082f49)'],['Candy','repeating-linear-gradient(45deg,#ffb3d1 0 20px,#fff 20px 40px)'],['Checker','conic-gradient(#f2f2f2 25%,#2fe68a 0 50%,#f2f2f2 0 75%,#2fe68a 0) 0 0/64px 64px'],['Aurora','radial-gradient(circle at 20% 20%,#34d399aa,transparent 40%),radial-gradient(circle at 80% 30%,#818cf8aa,transparent 45%),#0b1020'],['Charcoal','#1b1b1f'],['Lavender','linear-gradient(135deg,#c4b5fd,#7c3aed)']];
const IC={};(()=>{const px=(r,p)=>{const c=document.createElement('canvas');c.width=r[0].length;c.height=r.length;const x=c.getContext('2d');r.forEach((l,y)=>[...l].forEach((h,i)=>{if(p[h]){x.fillStyle=p[h];x.fillRect(i,y,1,1)}}));return c.toDataURL()};
IC.fw=px(['.GGGGGGGG.','GGGGGGGGGG','GGGGGWGGGG','GGGGWWGGGG','GGGWWGWGGG','GWGWWGWWGG','GWWWGGGWWG','GGWGGGGGWG','GGGGGGGGGG','.GGGGGGGG.'],{G:'#2fe68a',W:'#fff'});
IC.store=px(['...BBBB...','..B....B..','..B....B..','OOOOOOOOOO','OOOOOOOOOO','OOOWOOWOOO','OOOOOOOOOO','OOOOOOOOOO','OOOOOOOOOO','OOOOOOOOOO'],{B:'#5a3320',O:'#f08a24',W:'#fff'});
IC.amz=px(['..........','.TTTTTTTT.','TTTTTTTTTT','TDDDDDDDDT','TTTTSSTTTT','TTTTSSTTTT','TTTTTTTTTT','TTTTTTTTTT','TTTTTTTTTT','.TTTTTTTT.'],{T:'#c8964a',D:'#9a6b2c',S:'#e8d9a0'});
IC.ig=px(['.PPPPPPPP.','PPPPPPPPPP','PPPWWWWPPP','PPWPPPPWPP','PPWPWWPWPP','PPWPWWPWPP','PPWPPPPWPP','PPPWWWWPPP','PPPPPPPPPP','.PPPPPPPP.'],{P:'#d6249f',W:'#fff'});
IC.eats=px(['..........','..BBBBBB..','.BBsBBsBB.','.BBBBBBBB.','.GGGGGGGG.','.CCCCCCCC.','.RRRRRRRR.','.BBBBBBBB.','..BBBBBB..','..........'],{B:'#d89b4a',s:'#fff3c4',G:'#4caf50',C:'#f5c542',R:'#5a3320'});
IC.heart=px(['.RR..RR.','RRRRRRRR','RRRRRRRR','RRRRRRRR','.RRRRRR.','..RRRR..','...RR...','........'],{R:'#ff3b5c'});
IC.chat=px(['.WWWWWW.','W......W','W......W','W......W','.WWWWWW.','..WW....','.W......','........'],{W:'#ddd'});
IC.send=px(['........','WW......','WWWW....','WWWWWW..','WWWWWWWW','WWWWWW..','WW......','........'],{W:'#ddd'});IC.search=px(['..KKK...','.K...K..','K.....K.','K.....K.','K.....K.','.K...K..','..KKK.K.','.....K.K'],{K:'#111'});IC.msg=px(['BBBBBBBBBB','BWBBBBBBWB','BWWBBBBWWB','BWWWBBWWWB','BWWWWWWWWB','BWWBWWBWWB','BWBBBBBBWB','BBBBBBBBBB'],{B:'#3b82f6',W:'#fff'});IC.cars=px(['..........','...RRRR...','..RRWWRR..','.RRRRRRRR.','RRRRRRRRRR','RKKRRRRKKR','.KK....KK.'],{R:'#e74c3c',W:'#9ad0f5',K:'#111'});IC.prop=px(['....RR....','...RRRR...','..RRRRRR..','.RRRRRRRR.','..BBBBBB..','..BBWWBB..','..BBWWBB..','..BBBDDB..'],{R:'#c0392b',B:'#e8d9a0',W:'#7fc8f8',D:'#6b4a2e'});IC.pets=px(['.PP....PP.','.PP.PP.PP.','....PP....','..PPPPPP..','.PPPPPPPP.','.PPPPPPPP.','..PP..PP..'],{P:'#e39b5b'});IC.guard=px(['.SSSSSSSS.','SSSSWWSSSS','SSSWWWWSSS','SSSSWWSSSS','.SSSWWSSS.','..SSSSSS..','...SSSS...'],{S:'#4a6fa5',W:'#fff'})})();
const FOODM=[[[.9,.24,.9,'#d89b4a',0,.12,0],[.85,.18,.85,'#5a3320',0,.33,0],[.95,.05,.95,'#f5c542',0,.46,0],[1,.08,1,'#4caf50',0,.52,0],[.9,.3,.9,'#d89b4a',0,.7,0],[.1,.03,.1,'#fff3c4',.2,.86,.1],[.1,.03,.1,'#fff3c4',-.2,.86,-.1]],
[[1,.5,1,'#b03a2e',0,.25,0],[.9,.06,.9,'#e8b04a',0,.52,0],[.6,.1,.6,'#f4e19c',0,.6,0],[.25,.15,.25,'#fff',.2,.66,.1],[.05,.35,.4,'#1d3b2a',-.25,.75,0]],
[[1,.35,1,'#ddd',0,.18,0],[.9,.2,.9,'#4caf50',0,.45,0],[.4,.15,.4,'#e53935',.2,.6,.1],[.3,.12,.3,'#fbc02d',-.2,.58,-.1]],
[[.45,.9,.45,'#c0c6cc',0,.45,0],[.46,.4,.46,'#1e88e5',0,.45,0],[.2,.15,.47,'#fdd835',0,.45,0]],
[[1.4,.12,1,'#333',0,.06,0],[.5,.2,.5,'#fff',-.35,.22,-.2],[.5,.12,.3,'#ff7043',.3,.18,-.25],[.4,.15,.4,'#8bc34a',-.3,.2,.28],[.4,.15,.4,'#795548',.3,.2,.28]]];
let PVR,PVS,PVC;const PVM={};
function pvInit(){PVR=new THREE.WebGLRenderer({alpha:true,preserveDrawingBuffer:true});PVR.setSize(64,64);PVS=new THREE.Scene();PVS.add(new THREE.AmbientLight(0xffffff,.7));const l=new THREE.DirectionalLight(0xffffff,.8);l.position.set(3,6,5);PVS.add(l);PVC=new THREE.OrthographicCamera(-1.3,1.3,1.3,-1.3,-10,10);PVC.position.set(2,1.6,2);PVC.lookAt(0,0,0)}
function pvModel(k){if(PVM[k])return PVM[k];const[t,i,l]=k.split(':'),w=new THREE.Group(),g=new THREE.Group();(t=='f'?F[i].b:t=='e'?FOODM[i]:t=='a'?APPMOD[i]:t=='c'?carb(+i):t=='h'?hseb(+i):t=='p'?petb(+i):t=='k'?clb(i):gm(i,+l)).forEach(a=>B(g,...a));const bb=new THREE.Box3().setFromObject(g),c=bb.getCenter(new THREE.Vector3()),z=bb.getSize(new THREE.Vector3());g.position.sub(c);w.add(g);w.scale.setScalar(1.6/Math.max(z.x,z.y,z.z));return PVM[k]=w}
function pvLoop(){requestAnimationFrame(pvLoop);if(mode!='pc'&&!document.querySelector('.wrd')){if(PVT)PVT.style.display='none';return}const cs=[...document.querySelectorAll('canvas.pv')];if(HV&&PVT)cs.push(PVT);if(!cs.length)return;if(!PVR)pvInit();cs.forEach(c=>{const k=c===PVT?HV:c.dataset.k,az=c.closest&&c.closest('.azc,.uec,.lst,.thc2'),hov=c===PVT||(az&&az.matches(':hover')),m=(!hov&&c.dataset.d)?null:pvModel(k),x=c.getContext('2d');if(!m)return;c.dataset.d=1;PVS.add(m);m.rotation.y=hov?performance.now()/700:.7;PVR.render(PVS,PVC);x.clearRect(0,0,64,64);x.drawImage(PVR.domElement,0,0);PVS.remove(m)})}
const pvc=(k,z=128)=>`<canvas class=pv data-k="${k}" width=64 height=64 style="width:${z}px;height:${z}px;image-rendering:pixelated;display:block;margin:0 auto 8px;background:var(--pvb,#0006);border-radius:6px"></canvas>`;
let smo=0,wpo=null,dg=null;
function ds(e,k,x,y){dg={k,sx:e.clientX,sy:e.clientY,ox:x,oy:y,m:0,el:e.currentTarget}}
addEventListener('pointermove',e=>{if(!dg)return;const dx=e.clientX-dg.sx,dy=e.clientY-dg.sy;if(Math.abs(dx)+Math.abs(dy)>4)dg.m=1;if(dg.m){dg.el.style.left=(dg.ox+dx)+'px';dg.el.style.top=(dg.oy+dy)+'px'}});
addEventListener('pointerup',e=>{if(!dg)return;const d=dg;dg=null;if(d.m){S.ipos[d.k]=[Math.max(0,Math.min(innerWidth-90,d.ox+e.clientX-d.sx)),Math.max(0,Math.min(innerHeight-130,d.oy+e.clientY-d.sy))];pcR()}});
addEventListener('contextmenu',e=>{if(mode=='pc'){e.preventDefault();if(e.target.id=='pc'){wpo=[e.clientX,e.clientY];smo=0;pcR()}}});
function pcR0(){if(app&&!OA.includes(String(app)))OA.push(String(app));const tv0=$('cin')?$('cin').value:'';const nav=[['home','Artist page'],['upload','Upload'],['stats','Stats'],['albums','Albums']];let t='',b='',sb='';
 const ik=k=>k==1?'fw':k,nm=k=>k==1?'Spotifly':k=='store'?'App Barn':k=='msg'?'Messages'+(unr()?' ('+unr()+')':''):BI[k]||APPD[k].n,keys=[1,'store','web','msg','gear',...Object.keys(S.apps)];
 if(app==1){t='Spotifly';b=PG[S.artist?pg:'setup']();if(S.artist)sb=`<div class=sb><img class=pf style="width:48px;height:48px" src="${pfp()}"><h3>≋ Spotifly</h3>${nav.map(n=>`<button class="${pg==n[0]?'on':''}" onclick="pg='${n[0]}';pcR()">${n[1]}${n[0]=='upload'&&S.drafts.length?' ('+S.drafts.length+')':''}</button>`).join('')}</div>`}
 else if(app){t=nm(app);b=PA[app]()}
 const icons=keys.map((k,i)=>{const q=S.ipos[k]||[20,20+i*100];return`<div class=ico style="left:${q[0]}px;top:${q[1]}px" onpointerdown="ds(event,'${k}',${q[0]},${q[1]})" ondblclick="app='${k}';smo=0;pcR()"><img src="${IC[ik(k)]}">${nm(k)}${k=='msg'&&unr()?'<i class=ndot></i>':''}</div>`}).join('');
 const win=app?`<div class=win><div class=wt><span style="display:flex;gap:8px;align-items:center"><img src="${IC[ik(app)]}" style="width:18px;image-rendering:pixelated"><b>${t}</b></span><span><button onclick="app=0;pcR()">_</button> <button onclick="OA=OA.filter(k=>k!=app);app=0;pcR()">X</button></span></div><div class=wb>${sb}<div class="mn ${app=='amz'||app=='eats'||app=='msg'||app=='web'?'p0':''}">${b}</div></div></div>`:'';
 const tb=`<div class=tb><button class=go onclick="smo=!smo;pcR()" style="display:flex;gap:6px;align-items:center"><img src="${IC.fw}" style="width:18px;image-rendering:pixelated">Start</button>${OA.map(k=>`<button class="${k==app?'on':''}" onclick="app='${k}';smo=0;pcR()">${nm(k)}${k=='msg'&&unr()?'<i class=ndot></i>':''}</button>`).join('')}<span style="flex:1"></span><span>Day ${S.day} · ${clk()}</span></div>`;
 const start=smo?`<div class=sm>${keys.map(k=>`<button onclick="app='${k}';smo=0;pcR()"><img src="${IC[ik(k)]}">${nm(k)}</button>`).join('')}<button onclick="closePC()">Shut down</button></div>`:'';
 const wpp=wpo?`<div class=wpp style="left:${Math.max(0,Math.min(wpo[0],innerWidth-360))}px;top:${Math.max(0,Math.min(wpo[1],innerHeight-300))}px"><b>Desktop wallpaper</b><div class=wg>${WP.map((w,i)=>`<div class="wt2 ${S.wp==i?'on':''}" style="background:${w[1]}" onclick="S.wp=${i};pcR()"><span>${w[0]}</span></div>`).join('')}</div></div>`:'';
 $('ui').innerHTML=`<div id=pc style="background:${WP[S.wp][1]}" onpointerdown="if(event.target.id=='pc'&&(smo||wpo)){smo=0;wpo=null;pcR()}">${icons}${win}${wpp}${start}${tb}</div>`;$('pc').style.cursor=CUR;const cv=$('cv');if(cv)cv.scrollTop=cv.scrollHeight;const ci=$('cin');if(ci){ci.value=tv0;ci.focus()}}
const PA={store:()=>`<h1><img src="${IC.store}" style="width:32px;image-rendering:pixelated;vertical-align:middle"> App Barn</h1><p class=m>Balance ${$$(S.money)}. Apps cost real money here. Yee-haw.</p>${Object.keys(APPD).map(k=>{const a=APPD[k];return`<div class=card data-pv="a:${k}" style="margin:8px 0;display:flex;gap:12px;align-items:center"><div style="flex:1"><b style="font-size:16px;color:var(--t)">${a.n}</b><br><span class=m>${a.d}</span></div>${S.apps[k]?`<button onclick="app='${k}';pcR()">Open</button>`:`<button class=go ${S.money<a.p?'disabled':''} onclick="inst('${k}')">${$$(a.p)}</button>`}</div>`}).join('')}`,
amz:()=>`<h1>Amazoom</h1><p class=m>Balance ${$$(S.money)} · Press <b>F</b> in your house to place furniture. Models spin so you know what you are buying.</p><div class=cards style="grid-template-columns:repeat(auto-fill,minmax(160px,1fr))">${Object.keys(F).map(k=>`<div class=card>${pvc('f:'+k)}<b style="font-size:15px;color:var(--t)">${F[k].n}</b><p class=m>In storage: ${S.inv[k]||0}</p><button class=go ${S.money<F[k].p?'disabled':''} onclick="buyF('${k}')">${$$(F[k].p)}</button></div>`).join('')}</div>`,
eats:()=>`<h1>Goober Eats</h1><p class=m>Energy ${S.energy}/100 · Balance ${$$(S.money)}</p><div class=cards style="grid-template-columns:repeat(auto-fill,minmax(160px,1fr))">${FOOD.map((f,i)=>`<div class=card>${pvc('e:'+i)}<b style="font-size:15px;color:var(--t)">${f[0]}</b><p class=m>+${f[2]} energy</p><button class=go ${S.money<f[1]?'disabled':''} onclick="order(${i})">${$$(f[1])}</button></div>`).join('')}</div>`,
ig:()=>{if(!IGF.length)genFeed();const gi=(k,c='')=>`<img src="${IC[k]}" class="gi ${c}">`;
 return`<div style="max-width:440px;margin:0 auto;background:#000;border:1px solid #333;border-radius:6px"><div style="padding:10px 14px;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #262626"><span style="font:700 22px Silkscreen,monospace;background:linear-gradient(45deg,#f9a825,#e91e63,#7b1fa2);-webkit-background-clip:text;color:transparent">Instagrime</span><span style="display:flex;gap:10px">${gi('heart','lk')}${gi('send','lk')}</span></div>
 
 <div style="padding:10px 14px;border-bottom:1px solid #262626"><b>Promote your songs</b>${S.songs.length?S.songs.map(s=>`<div class=ng><span style="flex:1">${esc(s.title)}${s.boost>0?' [PROMOTED]':''}</span><button class=go ${S.money<PROMO||s.boost>0?'disabled':''} onclick="promo(${s.id})">Promote $${PROMO}</button></div>`).join(''):'<p class=m>Upload a song first.</p>'}<small class=m>Boosts streams for the next 3 nights.</small></div>
 ${IGF.map(p=>`<div class=post><div class=ph><div class=av>${esc(p.u[0].toUpperCase())}</div><b>${esc(p.u)}</b></div><div class=pbody style="background:linear-gradient(${p.a}deg,${p.c1},${p.c2})">${esc(p.cap)}</div><div class=acts><span onclick="this.firstChild.classList.toggle('lk')">${gi('heart')}</span>${gi('chat','lk')}${gi('send','lk')}</div><div class=ln><b>${p.l.toLocaleString()} likes</b></div><div class=ln><b>${esc(p.u)}</b> ${esc(p.tag)}</div><div class="ln m"><small>View all ${p.cm} comments</small></div></div>`).join('')}<div style="padding:10px"><button onclick="IGF=[];pcR()">Refresh feed</button></div></div>`}};
function genFeed(){const U=['Lil','Yung','Big','MC','Young','DJ','Baby','Sir'],V=['Cheddar','Soggy Biscuit','Blender','Spoon','Waffle','Noodle','Pickle','Crouton','Toaster','Meatball'],C=['Dropped a mixtape recorded inside a fridge','New single: my cat is my manager','No cap, just croutons','Studio session (it is my closet)','19 bars about parking tickets','Collab with a very patient pigeon','Just hit 12 followers, 11 are my mom','Rapping about soup again'],T=['#fridgecore #mixtape','#catmanager #drop','#crouton #nocap','#closetstudio','#parking #bars','#pigeon #collab','#mom #grind','#soup #flow'];IGF=[];for(let i=0;i<6;i++){const j=RI(0,7);IGF.push({u:(pick(U)+pick(V)).replace(/ /g,'_').toLowerCase(),cap:C[j],tag:T[j],c1:'hsl('+RI(0,360)+',70%,45%)',c2:'hsl('+RI(0,360)+',70%,25%)',a:RI(0,360),l:RI(20,90000),cm:RI(0,900)})}}
