/* ---------- v21 ---------- */
let WK=0,WGX=0,WEXT=null,WIN=null;const WING={ints:[],tvs:[]};
function FIN(x,r,h,kd){FIN0(x,r,h,kd);try{POSTFX(x.canvas)}catch(e){}}
function POSTFX(c){const W=c.width,H=c.height,x=c.getContext('2d');x.save();x.setTransform(1,0,0,1,0,0);const im=x.getImageData(0,0,W,H),d=im.data,o=new Uint8ClampedArray(d),Lm=i=>o[i]*.3+o[i+1]*.59+o[i+2]*.11,sw=W*4;
 for(let y=0;y<H;y++)for(let X=0;X<W;X++){const i=(y*W+X)*4,l=Lm(i);let e=0;[X+2<W?i+8:i,X>=2?i-8:i,y+2<H?i+2*sw:i,y>=2?i-2*sw:i].forEach(j=>{const q=Lm(j)-l;if(q>e)e=q});const u=X/W,v=y/H,lt=1.12-.3*Math.hypot(u-.3,v-.2)+(e>50?-.38:0)+(e>22&&e<=50?-.08:0);for(let k=0;k<3;k++)d[i+k]=Math.max(0,Math.min(255,(l+(o[i+k]-l)*1.14)*lt))}
 x.putImageData(im,0,0);
 const sm=document.createElement('canvas');sm.width=W/4;sm.height=H/4;const sx=sm.getContext('2d');sx.drawImage(c,0,0,sm.width,sm.height);const sd=sx.getImageData(0,0,sm.width,sm.height),q=sd.data;for(let i=0;i<q.length;i+=4){const l=q[i]*.3+q[i+1]*.59+q[i+2]*.11,k=l>215?1:0;q[i]*=k;q[i+1]*=k;q[i+2]*=k}sx.putImageData(sd,0,0);
 x.globalCompositeOperation='lighter';x.globalAlpha=.22;x.imageSmoothingEnabled=true;x.drawImage(sm,0,0,W,H);x.globalCompositeOperation='source-over';x.globalAlpha=1;x.restore()}
/* chat */
const FAVF=['jollof rice','cheese toasties','a proper full english','spicy ramen','pancakes','mac and cheese','dumplings','chips with way too much gravy'],FAVC=['teal','burnt orange','forest green','electric purple','mustard yellow','navy'],FAVS=['an old soul record my gran played','that one track you cannot stop looping','anything with a heavy bassline','a lo-fi tape I found in a charity shop'],JOKES=['why did the guitarist get arrested? for fretting a crime.','I told my drummer a joke once. he did not get it until the next day. rimshot.','what do you call a singer with no ideas? a hum-an.','my mic and I had a fight. now we are not on speaking terms.'];
const XSTOP=/^(the|a|an|and|but|for|with|about|that|this|you|your|what|when|where|how|are|was|were|have|has|had|just|really|very|like|them|they|there|here|some|from|into|then|than|its|it's|i'm|im|dont|don't|can|could|would|should|does|did|will|not|too|get|got|let|say|said|one|all|any|out|our|him|her|she|his|who|why|yes|yeah|okay|ok)$/;
const XI=[
['ai',/\b(are you (real|a bot|an ai|human|fake)|real person|chatbot)\b/,c=>['ha, I am a fictional stand-in inside a game, but I am doing my best to be good company.','real enough to pay you the featured fee, anyway.','a pixel person with opinions. that is as real as it gets here.']],
['age',/\b(how old|your age|what age|birthday)\b/,c=>['old enough to know better, young enough to ignore it.','I stopped counting after the third studio tour.','age is just a number, and mine is a secret.']],
['single',/\b(girlfriend|boyfriend|partner|single|dating|married|crush|relationship|wife|husband)\b/,c=>['ha, nice try. my love life is strictly off the record.','too busy with the music for all that. you?','keeping that one private. what about you, anyone special?']],
['doing',/\b(what are you (doing|up to)|wyd|what you doing|whatcha doing|what'?s going on|what you up to)\b/,c=>S.t<300?['just woke up, making tea and scribbling lyrics.','heading to the studio soon. what about you?','morning routine: coffee, stretch, ignore messages. you caught me.']:['winding down with a fresh beat on repeat.','sat on the sofa, half watching TV, half writing.','late session. my neighbours hate me. you?']],
['food',/\b(hungry|eat|ate|lunch|dinner|breakfast|snack|pizza|food|cook|coffee|tea|burger|meal|brunch)\b/,c=>['I could murder some '+FAVF[hs(c.n+c.g)%FAVF.length]+' right now.','food chat? now we are talking. what is your go-to?','honestly my fridge has three things in it and one is hot sauce.','coffee first, everything else second.']],
['fav',/\b(favou?rite|best (song|album|food|colou?r|film|movie|game))\b/,c=>['my favourite colour is '+FAVC[hs(c.g+c.n)%FAVC.length]+'. do not ask why.','hard to pick, but I always go back to '+FAVS[hs(c.n)%FAVS.length]+'.','ask me tomorrow and the answer changes. today it is '+FAVF[hs(c.g)%FAVF.length]+'.']],
['joke',/\b(joke|funny|make me laugh|riddle)\b/,c=>JOKES],
['sad',/\b(sad|tired|exhausted|stressed|stress|depressed|anxious|down|awful|terrible|rough day|bad day|lonely|burnt out|burned out|struggling)\b/,c=>['hey, that sounds heavy. take a breath, and a proper break if you can.','sorry you are feeling that way. want to talk about it or take your mind off it?','rest counts as work too, honestly. go easy on yourself.','I have been there. it does pass. what would help most right now?']],
['happy',/\b(great news|good news|got a|just (got|hit|finished|released|signed)|excited|so happy|best day|we did it|celebrate|made it)\b/,c=>['that is huge, congratulations!','yes! you deserve it. celebrate a little.','love that for you. tell me everything.']],
['weather',/\b(weather|rain|raining|sunny|snow|cold|freezing|hot|warm|storm|windy)\b/,c=>['weather like this is perfect for staying in and writing.','I never check the forecast, I just look out the window and complain.','rain makes the best demos, I swear.']],
['pet',/\b(dog|cat|puppy|kitten|pet|pets|hamster|parrot|bird|rabbit)\b/,c=>S.pets.length?['you have '+S.pets.length+' pet'+(S.pets.length>1?'s':'')+' now, right? lucky. they must love the studio.','pets make everything better. does yours try to sing along?']:['I would love a pet. maybe you should get one for the studio.','animals are the best audience, zero critics.']],
['car',/\b(car|cars|driving|drive|motor|ride|garage|wheels|vroom)\b/,c=>S.cars&&S.cars.length?['nice, you have '+S.cars.length+' car'+(S.cars.length>1?'s':'')+'. take me for a spin sometime.','a fast car and a good playlist is a full personality.']:['I still get the bus most days, honestly. no shame.','you should save up for a car. road trip album?']],
['home',/\b(house|home|flat|apartment|mansion|villa|penthouse|move|upstairs|garden|neighbou?r)\b/,c=>(S.home||0)>=1?['I heard you upgraded the place. I want a tour.','a bigger home means a bigger sound. suits you.']:['your place is cosy, I like it. but a bigger studio would be fun too.','home is where the mic is.']],
['fame',/\b(famous|fame|viral|followers|listeners|streams|popular|chart|charts|blow up|blowing up|number one|no\.? ?1)\b/,c=>['you are at '+c.lis+' listeners. that is real momentum.','fame is loud. keep the music louder.','everyone starts small. you are already past that.','charts are nice, but the next song is what matters.']],
['insta',/\b(insta|instagrime|post|posted|photo|pic|picture|selfie|followers|story)\b/,c=>['I saw your last post, the pixels were crisp.','I stalk your feed more than I admit. good stuff.','selfie game strong. keep posting.']],
['advice',/\b(advice|help me|what should i|should i|what do you think|any tips|tips|how do i|how to)\b/,c=>['honestly? finish the song, polish it later.','keep your circle small and your sessions long.','release more than you think you should. you learn from every single one.','take the collab, learn something, then take the next.','trust your ears, not the numbers.']],
['hobby',/\b(hobbies|hobby|free time|weekend|gaming|games|football|gym|movies|film|series|netflix|read|book|sport)\b/,c=>['I play way too many games and call it research.','weekends are for sleeping, snacks and reworking old songs.','I am a film nerd. nothing beats a good soundtrack.','gym when I feel guilty, sofa when I do not.']],
['travel',/\b(tour|travel|holiday|vacation|abroad|flight|plane|trip|festival)\b/,c=>['I want a festival run next summer. you in?','touring is 10% stage, 90% waiting in vans.','one day, a tour bus with a proper kitchen. dream big.']],
['sleep',/\b(sleep|nap|bed|awake|insomnia|late night|up late|morning|early)\b/,c=>['sleep is for people without deadlines. I am joking, go to bed.','my best lyrics come at 3am and make no sense at 9.','I am a night person, sorry not sorry.']],
['name',/\b(my name is|call me|i'?m called|i am called)\s+([a-z]+)/,c=>null],
['thanks2',/\b(you'?re (the best|awesome|great|amazing|cool)|i like you|miss you|good talk)\b/,c=>['aw, that means a lot. you are not so bad yourself.','ha, stop it, you are making me blush.','same here. this was a good one.']],
['studio',/\b(studio|record|recording|mic|microphone|guitar|piano|drums|bass|mixing|mastering|producer)\b/,c=>['I live in the studio. my sofa has a dent.','the right mic changes everything, trust me.','I mix until my ears ring and then do it again.','bring a spare guitar string, you will thank me.']]
];
function xr(m,t,n){const a=ART[m.a],c=ctxOf(m);for(const k of XI){const q=n.match(k[1]);if(!q)continue;if(k[0]=='name'){S.nick=q[2][0].toUpperCase()+q[2].slice(1);return 'nice to meet you properly, '+S.nick+'.'}const o=k[2](c);if(o)return pick(o)+((Math.random()<.35&&!['advice','joke','happy','name'].includes(k[0]))?' '+pick(['what about you?','how is your day going?','you working on anything new?','what are you into lately?']):'')}
 const w=n.replace(/[^a-z0-9' ]/g,' ').split(/\s+/).filter(x=>x.length>3&&!XSTOP.test(x));if(w.length&&n.split(/\s+/).length>=3&&Math.random()<.6){const k=w.sort((p,q)=>q.length-p.length)[0];return pick(['I have never really thought about '+k+' that much, tell me more.','ha, '+k+'. that is a whole mood.','funny you mention '+k+', I was just thinking something similar.','honestly '+k+' is underrated.','go on, what is it about '+k+' for you?'])}return null}
{const rp0=reply;reply=function(m,t){const n=NZ(t),tg=IR.filter(r=>r[1].test(n)).map(r=>r[0]);const ng=m.stage>0||m.state>0;if(m.a!==undefined&&!tg.some(k=>['bye','rude','collab'].includes(k))&&!(ng&&tg.some(k=>['yes','no','pay','haggle','later','cancel'].includes(k)||(m.state==1&&['where','when'].includes(k))))){const r=xr(m,t,n);if(r){TY=0;m.rel=(m.rel||0)+1;if(m.state==2)m.state=0;const a=ART[m.a],c=ctxOf(m);if(S.nick)c.n=S.nick;m.log.push({f:'a',t:deco(a,fill(r,c)),d:S.day});if(m.rel>=4&&!m.asked&&m.stage==0&&m.state==0&&Math.random()<.4){m.asked=1;m.stage=1;m.log.push({f:'a',t:deco(a,fill(pick(RB.ask),c)),d:S.day})}return}}rp0(m,t)}}
/* wardrobe */
function wrR(){const own=GAR.filter(g=>S.wr.includes(g.id)&&g.slot==WT),wn=S.wn||{},sc=(document.getElementById('wrg')||{}).scrollTop||0,cnt=k=>GAR.filter(g=>S.wr.includes(g.id)&&g.slot==k).length;
 $('ui').innerHTML=`<div class="box modal wrd"><div class=wrh><h2>Wardrobe</h2><span class=m>${S.wr.length} pieces owned</span><button onclick="closeUI()" style="margin-left:auto">Close ✕</button></div><div class=wrw>${WSL2.map(t=>{const id=wn[t[0]],g=id&&GM[id];return`<div class="wrs ${g?'on':''}" onclick="WT='${t[0]}';wrR()"><small>${t[1]}</small><b>${g?esc(g.n):'nothing'}</b>${g&&t[0]!='top'?`<i onclick="event.stopPropagation();unq('${t[0]}')">take off</i>`:''}</div>`}).join('')}</div><div class=wrt>${WSL2.map(t=>`<button class="${WT==t[0]?'go':''}" onclick="WT='${t[0]}';wrR()">${t[1]} (${cnt(t[0])})</button>`).join('')}</div><div id=wrg class="thg wrg">${own.map(g=>{const cur=(S.wc||{})[g.id]||g.dc,on=wn[g.slot]==g.id;return`<div class="thc2 ${on?'worn':''}"><div class=thp style="--pvb:transparent">${pvc('k:'+g.id+'|'+cur,150)}</div><div class=thn>${esc(g.n)}${on?' <small style="color:#d81b60">· wearing</small>':''}</div><div class=thsw>${CPAL.map(c=>`<i class="${c==cur?'on':''}" style="background:${c}" onclick="(S.wc=S.wc||{})['${g.id}']='${c}';${on?`wearG('${g.id}','${c}');`:''}wrR()"></i>`).join('')}</div><button class=go onclick="wearG('${g.id}');wrR()">${on?'Wearing ✓':'Wear'}</button></div>`}).join('')||'<p class=m style="grid-column:1/-1">Nothing here yet. Buy clothes on the Threadz website (laptop, Browser). Every piece you own can be recoloured here for free.</p>'}</div></div>`;const g=document.getElementById('wrg');if(g)g.scrollTop=sc}
{const st=document.createElement('style');st.textContent='.wrd{width:min(1040px,96vw);max-height:92vh;display:flex;flex-direction:column;gap:10px}.wrh{display:flex;align-items:center;gap:14px}.wrh h2{margin:0}.wrw{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.wrs{border:2px solid #111;background:#1d2a24;padding:6px 8px;cursor:pointer;display:flex;flex-direction:column;gap:2px;font-size:12px;min-width:0}.wrs.on{border-color:#ff3d81}.wrs b{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.wrs i{font-style:normal;color:#ff9fbf;text-decoration:underline;font-size:11px}.wrt{display:flex;flex-wrap:wrap;gap:6px}.wrg{overflow:auto;flex:1;min-height:200px;padding:4px;grid-template-columns:repeat(auto-fill,minmax(190px,1fr))!important}.wrg .thp canvas.pv{width:120px!important;height:120px!important}.thc2.worn{outline:4px solid #ff3d81}@media(max-width:700px){.wrw{grid-template-columns:repeat(3,1fr)}}';document.head.appendChild(st)}
/* home extension wing (built backwards, north of the house) */
function buildWing(){const L=Math.min(1,Math.max(0,(S.home||0)-1));if(L<1)return;if(!WEXT){WEXT=new THREE.Group();scene.add(WEXT);WIN=new THREE.Group();scene.add(WIN);WING.nw=[]}
 const g=WIN,put=(t,x,z,r)=>{if(!F[t])return;const m=mkF(t);m.position.set(x,0,z);m.rotation.y=r*Math.PI/2;scene.add(m);PL.push({t,x,z,r,m})};
 if(WK==0){NWM.forEach(q=>{if(q[1]==0){q[0].visible=false;const c=q[2];[[0,3.2],[4.7,8]].forEach(a=>B(g,a[1]-a[0],3,.3,c,(a[0]+a[1])/2,1.5,-.15));B(g,1.5,.6,.3,c,3.95,2.7,-.15);B(g,.12,2.4,.34,'#5a3a22',3.2,1.2,-.15);B(g,.12,2.4,.34,'#5a3a22',4.7,1.2,-.15)}});const i=cols.findIndex(c=>c[0]==0&&c[1]==-.3&&c[2]==16);if(i>=0)cols.splice(i,1,[0,-.3,3.2,.15],[4.7,-.3,16,.15])}
 while(WK<L){const k=WK++,zs=-6*(k+1),ze=-6*k,cz=zs+3,wl=['#d9c9a8','#cfd6c8','#c9c0d4','#d8c2a0'][k],fc=[['#8a6f5a','#75594a'],['#9a8aa8','#85758f'],['#8a9aa8','#75858f'],['#a8896a','#93745a']][k];
  const fl=new THREE.Mesh(geo(16,.2,6),tex(fc[0],fc[1],16,6));fl.position.set(8,-.1,cz);g.add(fl);
  B(g,.3,3,6,wl,-.15,1.5,cz);col(-.3,zs,0,ze);col(16,zs,16.3,ze);
  if(k>0){const o=WING.nw[k-1];o.m.visible=false;o.w.forEach(m=>m.visible=false);const i=cols.indexOf(o.c);if(i>=0)cols.splice(i,1)}
  const nm=B(g,16,3,.3,wl,8,1.5,zs-.15),nc=[0,zs-.3,16,zs],w1=B(g,1.8,1.1,.1,'*cfe8fa',4,1.8,zs-.02),w2=B(g,1.8,1.1,.1,'*cfe8fa',12,1.8,zs-.02);cols.push(nc);WING.nw.push({m:nm,c:nc,w:[w1,w2]});
  const pw=(x0,z0,x1,z1)=>{if(z0==z1){B(g,x1-x0,1.1,.24,'#cbbf9f',(x0+x1)/2,.55,z0);B(g,x1-x0,.06,.3,'#8a7a62',(x0+x1)/2,1.13,z0);col(x0,z0-.12,x1,z0+.12)}else{B(g,.24,1.1,z1-z0,'#cbbf9f',x0,.55,(z0+z1)/2);B(g,.3,.06,z1-z0,'#8a7a62',x0,1.13,(z0+z1)/2);col(x0-.12,z0,x0+.12,z1)}};
  pw(8,zs,8,zs+2.6);pw(8,zs+4.2,8,ze);if(k>=1){pw(0,ze,3.2,ze);pw(4.7,ze,11,ze);pw(12.5,ze,16,ze)}
 }
 WEXT.clear();const D=6*L,e=WEXT,wl='#d8c7a6',rf='#8d2d2d';B(e,.3,3,D,wl,16.15,1.5,-D/2);for(let k=0;k<L;k++)[2,4].forEach(z=>B(e,.1,1.1,1.8,'#9ad0f5',16.32,1.7,-6*k-z));B(e,17.4,.3,D+.6,rf,8,3.15,-D/2+.3);B(e,10,.3,D+.4,dk(rf,.8),8,3.45,-D/2+.2);WGX=D}
{const wt4=worldTick;worldTick=function(dt){if(WK<Math.min(1,Math.max(0,(S.home||0)-1)))buildWing();wt4(dt);if(WEXT)WEXT.visible=HX.visible;if(WIN)WIN.visible=true}}
{const tv1=tvTick;tvTick=function(dt){tv1(dt);const t=performance.now()/400;WING.tvs.forEach(m=>m.material.color.set(m.on?'hsl('+((t*40)%360|0)+',60%,'+(40+Math.sin(t*3)*12|0)+'%)':'#14181d'))}}


{const gu0=goUp;goUp=function(){gu0();if(hit(P.x,P.z,.28)){const bx=P.x,bz=P.z;let f=0;for(let r=.4;r<10&&!f;r+=.4)for(let a=0;a<12&&!f;a++){const x=bx+Math.cos(a*Math.PI/6)*r,z=bz+Math.sin(a*Math.PI/6)*r;if(!hit(x,z,.28)){P.x=x;P.z=z;f=1}}camT.x=P.x;camT.z=P.z}}}


