/* ---------- v26 ---------- */
/* energy costs: a collab session costs half of a solo session */
const REC_E=15,COLLAB_E=REC_E/2;

/* ===== 1. artist collabs ===== */
/* the player pays the artist's fee to book a collab; the fee is shown on a confirm button before it is taken */
RB.confirm=['sweet. my fee is ${pay}. hit confirm and I will see you {loc}.','deal, once the ${pay} fee is sorted we are on. confirm when you are ready.','love it. ${pay} and we are booked. confirm and I will meet you {loc}.'];
function refundM(m){if(m&&m.paid){S.money=+(S.money+m.paid).toFixed(2);say('Refunded '+$$(m.paid)+' collab fee.');m.paid=0}}
function payCollab(id){const m=S.msgs.find(x=>x.id==id);if(!m||m.state!=0||m.stage!=2||!m.ready)return;const a=ART[m.a];if(S.money<m.pay){snd('err');return say('Not enough money for the '+$$(m.pay)+' fee.')}
 S.money=+(S.money-m.pay).toFixed(2);m.paid=m.pay;m.state=1;m.ready=0;m.log.push({f:'a',t:deco(a,fill(pick(RB.deal),ctxOf(m))),d:S.day});syncArt();updateVersion();snd('cash');say('Paid '+$$(m.pay)+'. Go meet '+a[0]+' (gold beacon).');pcR()}
function unready(id){const m=S.msgs.find(x=>x.id==id);if(m)m.ready=0;pcR()}
{const rp=reply;reply=function(m,t){rp(m,t);const n=NZ(t);if(m.state==0&&IR.some(r=>(r[0]=='no'||r[0]=='cancel')&&r[1].test(n))&&!IR.some(r=>r[0]=='yes'&&r[1].test(n)))m.ready=0;
 if(m.want&&!m.asked&&m.stage==0&&m.state==0){m.asked=1;m.stage=1;m.log.push({f:'a',t:deco(ART[m.a],fill(pick(RB.ask),ctxOf(m))),d:S.day})}}}
/* contacts: red dot = genuinely wants to collab, blue = just chatting */
const wantA=i=>hs(ART[i][0])%3!=0,wantC=m=>m.a!==undefined&&m.state!=2&&m.state!=3&&!!(m.want||m.stage>=1||m.state==1);
const pdot=(src,red)=>`<span class=pfw><img src="${src}"><i class="cdot ${red?'r':'b'}" title="${red?'Wants to collab':'Just chatting'}"></i></span>`;
{const sc0=startChat;startChat=function(i){sc0(i);const m=S.msgs[S.msgs.length-1];if(m&&m.a===i&&wantA(i)){m.want=1;pcR()}}}
const NL2=()=>ART.map((a,i)=>S.listeners>=a[2]&&!S.msgs.some(m=>m.a===i)?`<div class=cr onclick="startChat(${i})">${pdot(pf2(a[4]),wantA(i))}<div class=t><b>${esc(a[0])}</b><small>${esc(a[1])} · ${wantA(i)?'open to a collab':'start a chat'}</small></div></div>`:'').join('')||'<div class=cr><small>Nobody new is reachable yet. Grow your listeners.</small></div>';
PA.msg=()=>{const L=S.msgs,cur=L.find(m=>m.id==S.chat)||L[L.length-1];S.chat=cur.id;cur.unread=0;const art=cur.a!==undefined,
 bar=art&&cur.state==0&&cur.stage==2&&cur.ready?`<div class=cfm><span>Collab fee <b>${$$(cur.pay)}</b> · you have ${$$(S.money)}</span><button class=go ${S.money<cur.pay?'disabled':''} onclick="payCollab(${cur.id})">Confirm &amp; pay ${$$(cur.pay)}</button><button onclick="unready(${cur.id})">Not now</button></div>`:'';
 return`<div class=chat><div class=cl><h2>Chats <button onclick="ncv=!ncv;pcR()" style="float:right;font-size:12px">+ New</button></h2><div class=crs>${ncv?NL2():''}${L.slice().reverse().map(m=>`<div class="cr ${m.id==cur.id?'on':''}" onclick="openChat(${m.id})">${m.a===undefined?`<img src="${cpic(m)}">`:pdot(cpic(m),wantC(m))}<div class=t><b>${esc(cname(m))}</b><small>${esc(clast(m))}</small></div>${m.unread?'<span class=ub>new</span>':''}</div>`).join('')}</div></div><div class=cv><div class=cvh>${art?pdot(cpic(cur),wantC(cur)):`<img src="${cpic(cur)}">`}<div><b>${esc(cname(cur))}</b><br><small style="color:#8aa094">${!art?'Official':esc(ART[cur.a][1])+' · '+(ART[cur.a][8]?'fictional in-game stand-in':'fictional artist')}${cur.state==1?' · collab booked, fee paid':cur.state==2?' · declined':cur.state==3?' · collab done':''}</small></div></div>
 <div class=cvb id=cv>${!art?`<div class="bb a">${esc(cur.body)}</div>`:cur.log.map(x=>`<div class="bb ${x.f}">${esc(x.t)}<small>Day ${x.d||''}</small></div>`).join('')}${TY==cur.id?'<div class="bb a"><i>typing…</i></div>':''}</div>
 ${bar}${!art?`<div class=cin><small style="padding:8px;color:#8aa094">Official account. No replies.</small></div>`:`<div class=cin><input id=cin placeholder="Type a message…" maxlength=140 onkeydown="if(event.key=='Enter')sendMsg()"><button class=go onclick="sendMsg()">Send</button></div>`}
 <div style="padding:4px 12px;font-size:11px;color:#8aa094;background:#16201b">Fictional in-game conversations. Real artist names are used for fictional stand-ins; no endorsement, no real music. You pay the artist's fee to book a collab.</div></div></div>`};
/* first in-game day: a few artists slide into your DMs, once per new game (saved, so a reload does not repeat it) */
const FDM={w:['saw you just set up your page. new artists are my favourite thing to find. want to make something together?','heard a rumour there is a new name in town. that you? we should cook something up.','just found your profile, the vibe is right. I have a beat with your name on it.'],f:['welcome to the scene! no pressure, just saying hi.','hey, new neighbour in the music world. good luck with the first track.','saw your page pop up. hope the first week treats you well.']};
function firstDMs(){S.dm1=1;const pool=ART.map((a,i)=>i).filter(i=>!ART[i][8]&&ART[i][2]<=60&&!S.msgs.some(m=>m.a===i)).sort(()=>Math.random()-.5),k=Math.min(pool.length,RI(2,3));
 pool.slice(0,k).forEach((i,j)=>{const a=ART[i],w=j<2,m={id:S.nid++,a:i,state:0,stage:w?1:0,ex:0,neg:0,pay:a[3],unread:1,log:[],rel:0,want:w?1:0,asked:w?1:0};m.log.push({f:'a',t:deco(a,pick(FDM[w?'w':'f'])),d:S.day});if(w)m.log.push({f:'a',t:deco(a,fill(pick(RB.ask),ctxOf(m))),d:S.day});S.msgs.push(m)});
 if(k){snd('ping');say(k+' artists messaged you. Check Messages on your computer.')}updateVersion()}
/* collab songs always carry exactly one "(feat. NAME)" */
const featT=(t,ft)=>String(t||'').replace(/\s*[([](feat|ft)\.?\s[^)\]]*[)\]]/gi,'').trim().replace(/^$/,'Untitled')+' (feat. '+ft+')';
{const st0=saveT;saveT=function(id){const d=S.drafts.find(x=>x.id==id),i=$('tin');if(d&&d.ft&&i&&i.value.trim())i.value=featT(i.value,d.ft);st0(id)}
 const up0=upl;upl=function(id){const d=S.drafts.find(x=>x.id==id);if(d&&d.ft&&d.title.trim())d.title=featT(d.title,d.ft);up0(id)}}
/* in-person meeting: three replies per exchange, 1-3 exchanges, each reply moves the artist's opinion */
const PERS={chill:'laid-back',hype:'high energy',shy:'shy',formal:'professional',goofy:'goofy'};
const TONE={hype:['Wassup! Let\'s cook something crazy today.','Yooo, finally! I\'ve been hyped for this all week.','Let\'s gooo, this track is gonna slap.','What\'s good! Turn it up, let\'s make noise.'],
 chill:['Hey, good to finally meet. No rush, let\'s just vibe.','All good, take your time. We\'ll find the groove.','Easy pace today. Let\'s see where the sound goes.','Nice to meet you properly. Coffee first?'],
 pro:['Thanks for coming. I\'ve got a plan for the hook, want to hear it?','I mapped out the structure: verse, hook, your verse, bridge.','Let\'s get levels checked and do a clean first take.','I prepped a reference track so we don\'t waste your time.'],
 joke:['Fair warning, my mic is held together with tape and hope.','If this flops, we blame the pigeon outside.','I practised my best studio face in the mirror. Rate it.','Snacks are on me. That\'s my whole budget gone.'],
 cocky:['Honestly, you\'re lucky to be on my track.','Just follow my lead and it\'ll be a hit.','My fans are gonna carry this one anyway.','Try to keep up, yeah?']};
const PREF={chill:{hype:0,chill:1,pro:0,joke:1,cocky:-1},hype:{hype:1,chill:-1,pro:0,joke:1,cocky:0},shy:{hype:-1,chill:1,pro:1,joke:0,cocky:-1},formal:{hype:-1,chill:0,pro:1,joke:-1,cocky:-1},goofy:{hype:1,chill:0,pro:-1,joke:1,cocky:-1}};
const OPEN={chill:['hey, you made it. no stress, the studio is all ours.','yo, good to see you in person. what is the vibe today?'],hype:['YOOO there they are! you ready to cook?!','LETS GO, the session is finally happening!'],shy:['oh, hi... um, thanks for booking this.','hey... sorry, I get a bit nervous meeting people. hi.'],formal:['Good to meet you in person. Shall we discuss the session?','Thank you for booking. I am ready when you are.'],goofy:['ahoy, collab buddy! I brought exactly zero snacks.','greetings, fellow human. the beat awaits.']};
const RCT={pos:{chill:['ha, I like that energy.','yeah, that feels right.'],hype:['THAT is what I am talking about!','YES, love it!!'],shy:['oh, that is... actually really nice.','okay, I feel a bit better now.'],formal:['Excellent, that is very sensible.','I appreciate that approach.'],goofy:['ha! you are my kind of weird.','okay that got a laugh out of me.']},
 neu:{chill:['mm, okay, cool.','fair enough.'],hype:['okay okay, sure.','alright, I hear you.'],shy:['um, okay.','sure, I guess.'],formal:['Understood.','Very well.'],goofy:['huh. okay then.','noted, captain.']},
 neg:{chill:['eh, bit much, but alright.','hm, that is not really my vibe.'],hype:['bro, where is the energy?','come on, that is kind of flat.'],shy:['oh... okay.','that is a bit intense for me.'],formal:['I would prefer we keep it focused.','That is not quite how I work.'],goofy:['wow, tough crowd.','okay, mister serious.']}};
const MID={chill:['so what kind of sound are you hearing?','how do you usually start a track?'],hype:['what is the big idea for the drop?!','how loud are we going?'],shy:['do you, um, want me on the hook or a verse?','should I warm up first?'],formal:['How would you like to split the verses?','Do you have a reference in mind?'],goofy:['should the song be about soup? asking seriously.','what if the chorus was just clapping?']};
const READY={chill:['alright, let us lay it down.'],hype:['okay, mics on, LETS RECORD!'],shy:['okay... I think I am ready.'],formal:['Shall we begin recording?'],goofy:['to the microphone, onward!']};
const opLbl=o=>o>=2?'loves you':o==1?'warming up':o==0?'neutral':o==-1?'unsure':'annoyed';
let MEET=null;
function mtOpts(){return Object.keys(TONE).sort(()=>Math.random()-.5).slice(0,3).map(t=>[t,pick(TONE[t])])}
function collab(o){const m=S.msgs.find(x=>x.a===o.i);if(!m)return;const a=ART[o.i];let op=0;if((m.rel||0)>=5)op++;if(m.neg)op--;MEET={o,m,a,n:RI(1,3),k:0,op,line:pick(OPEN[a[5]]),opts:mtOpts()};mode='menu';meetR()}
function meetR(){const M=MEET,a=M.a,done=M.k>=M.n;$('ui').innerHTML=`<div class="box modal mtg"><div class=mth><img src="${pf2(a[4])}"><div><b>${esc(a[0])}</b><br><small class=m>${esc(a[1])} · ${PERS[a[5]]} · opinion: <b>${opLbl(M.op)}</b></small></div></div><p class=mtl>"${esc(M.line)}"</p>${done?`<p class=m>Collab recording costs ${COLLAB_E} energy (half a solo session). You have ${Math.round(S.energy)}.</p><div class=row2><button class=go onclick="meetRec()">Start recording</button><button onclick="closeUI()">Later</button></div>`:M.opts.map((t,i)=>`<button class=mto onclick="meetPick(${i})">${esc(t[1])}</button>`).join('')+`<small class=m>Exchange ${M.k+1} of ${M.n} · pick a reply</small>`}</div>`}
function meetPick(i){const M=MEET;if(!M||M.k>=M.n)return;const t=M.opts[i][0],p=M.a[5];let d=PREF[p][t];
 /* context: bragging lands worse when they are bigger than you; hype lands worse late at night with laid-back or shy artists */
 if(t=='cocky'&&S.listeners<M.a[2])d--;if(t=='hype'&&S.t>=300&&(p=='chill'||p=='shy'))d--;if(t=='pro'&&M.m.neg&&p=='formal')d++;
 d=Math.max(-2,Math.min(2,d));M.op=Math.max(-3,Math.min(3,M.op+d));M.k++;M.line=pick(RCT[d>0?'pos':d<0?'neg':'neu'][p])+' '+pick(M.k<M.n?MID[p]:READY[p]);M.opts=mtOpts();snd(d>0?'ping':d<0?'err':'pop');meetR()}
function meetRec(){const M=MEET;if(!M)return;if(S.energy<COLLAB_E){snd('err');return say('Too tired to record, even a collab. Rest and come back.')}S.energy=Math.max(0,+(S.energy-COLLAB_E).toFixed(1));updateVersion();$('ui').innerHTML='';const o=M.o;mode='cut';cs2={o,t:0,op:M.op};P.x=o.x-1.4;P.z=o.z;P.rot=Math.PI/2;MEET=null;say('Recording with '+o.name+' (fictional)')}
collabDone=function(){const o=cs2.o,op=cs2.op||0,a=ART[o.i],m=S.msgs.find(x=>x.a===o.i);if(o.m.parent)o.m.parent.remove(o.m);if(m){m.state=3;m.doneDay=S.day;m.ready=0;m.paid=0;m.log.push({f:'a',t:deco(a,op>=1?'that session was great, thanks again!':op<=-1?'well, we got a track out of it.':'good session, thanks.'),d:S.day})}ART_M=ART_M.filter(x=>x!==o);
 const q=Math.max(5,Math.round(R(30,40)+S.gear.chair*4+S.gear.mic*8+S.gear.guitar*6+(S.home||0)*3)+Math.min(25,6+Math.round(a[3]/60))+op*4),
 d={id:S.nid++,title:featT(pick(A)+' '+pick(Bn),a[0]),g:a[1],q,ft:a[0],fm:+((1.1+Math.min(.6,a[3]/6000))*(1+op*.12)).toFixed(2),op,role:pick(['Featured verse','Co-writer and hook','Producer and beats','Backing vocals'])};
 S.drafts.push(d);updateVersion();cs2=null;snd('chime');nameModal(d,`<p style="color:var(--g)">Collab with ${esc(a[0])} done. Chemistry: <b>${opLbl(op)}</b>${op>0?' (better quality, more streams)':op<0?' (lower quality, fewer streams)':''}. Fictional in-game event with a stand-in character.</p>`)};
{const st=document.createElement('style');st.textContent='.pfw{position:relative;display:inline-block;flex-shrink:0;line-height:0}.cdot{position:absolute;top:0;right:0;width:11px;height:11px;border-radius:50%;border:2px solid #0d1411;box-sizing:border-box}.cdot.r{background:#ff3b5c}.cdot.b{background:#3b82f6}.cfm{display:flex;gap:8px;align-items:center;flex-wrap:wrap;padding:8px 12px;background:#16201b;border-top:1px solid #1a2520}.cfm span{flex:1}.mtg{width:min(480px,94vw)}.mth{display:flex;gap:12px;align-items:center}.mth img{width:56px;height:56px;border-radius:50%;image-rendering:pixelated;background:#2a4a38}.mtl{font-size:15px;margin:12px 0}.mto{display:block;width:100%;text-align:left;margin:6px 0}';document.head.appendChild(st)}

/* ===== per-frame hooks ===== */
{const u0=update;update=function(dt){u0(dt);if(mode=='play'&&S.day==1&&!S.dm1&&S.t>4)firstDMs()}}
